# Generated by Django 4.2.1 on 2024-05-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvermoon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergame',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
