# Generated by Django 4.2.1 on 2024-05-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silvermoon', '0003_alter_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='descriptionEng',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
